version: '3.7'
services:
  vue-chicken:
    container_name: vue-chicken
    image: chickenbastonwheaton:latest
    ports:
      - 2013:80
    volumes:
      - ./:/app/dist
    networks:
      - chicken
    environment:
      WEB_DOCUMENT_ROOT: /app

networks: 
  chicken:
    external:
      name: website